packaging_format = 2

id = " peppermint"
name = "Peppermint"
description.en = "Ticket management & help desk solution"
description.fr = "Ticket management & help desk solution"

version = "0.2.3~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "free"
website = "https://peppermint.sh/"
admindoc = "https://docs.peppermint.sh/"
code = "https://github.com/Peppermint-Lab/peppermint"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/Peppermint-Lab/peppermint/archive/refs/tags/0.2.3.tar.gz"
        sha256 = "0ec1c3feb3f7754373e340b2221e05ae6b6449a73fcf6d02a177a4593b659b9c"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "postgresql"
    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"

    [resources.database]
    type = "postgresql"
